version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_DB=blogvid
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root*123
    ports:
      - "5465:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3100:3100"
    links:
      - postgres
    depends_on:
      - postgres
    container_name: auth_api
    environment:
      WAIT_HOSTS: postgres:5465
      LOG_FILEPATH: '/app/app/logging/logs.log'
    volumes:
      - ./app/logging:/app/app/logging